# In order to build for staging run:
# $ jekyll build --config _config.yml, _config-production.yml
#
#
# URL of static site
url: "https://www.open-cmsis-pack.org"
# Destination folder
destination: production.open-cmsis-pack.org
# Production boolean used in layouts / includes
production: true
# Google Analytics
google_analytics:
  enabled: true
  code: G-HMVFZEVJSK
